name: odd
channels:
  - conda-forge
  - nodefaults
dependencies:
  # For development
  - wget
  - curl
  - jupyter
  - pip
  - pipx
  - uv
  - pixi
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-xdist
  - pytest-timeout
  # For development on the Hub
  - git
  - gh
  - code-server
  - jupyter-resource-usage
  - jupyter-vscode-proxy
  - pip:
      - gh-scoped-creds

